name: Substack RSS to n8n

on:
  workflow_dispatch:

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Fetch RSS and POST to n8n
        run: |
          python - <<EOF
          import feedparser
          import requests

          FEED_URL = "https://substack-feed-proxy.onrender.com/proxy"
          WEBHOOK_URL = "https://adambalm.app.n8n.cloud/webhook/content/v1/substack"

          try:
              headers = {"User-Agent": "Mozilla/5.0"}
              resp = requests.get(FEED_URL, headers=headers)
              print(f"Feed HTTP status: {resp.status_code}")
              feed = feedparser.parse(resp.text)
              print(f"Feed status: {feed.get('status')}")
              print(f"Feed bozo: {feed.get('bozo')}")
              if feed.get('bozo'):
                  print(f"Feed error: {feed.get('bozo_exception')}")
          except Exception as e:
              print(f"Failed to fetch feed: {e}")
              raise

          entries = feed.entries
          print(f"Fetched {len(entries)} entries from feed")

          for entry in entries:
              print(f"Preparing to post: {entry.title}")
              data = {
                  "title": entry.title,
                  "link": entry.link,
                  "published": entry.published,
                  "summary": entry.summary
              }
              try:
                  response = requests.post(WEBHOOK_URL, json=data)
                  print(f"Posted {entry.title}: {response.status_code} {response.text}")
              except Exception as e:
                  print(f"Error posting {entry.title}: {e}")

          print("Finished processing RSS feed")
          EOF
